name: CI

on:
  push:
    branches:
      - 'master'
      - 'dev'
      
env:
  NODE_VERSION: '14'

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{env.NODE_VERSION}}
        
    - name: Install
      run: npm ci
        
    - name: Lint
      run: npm run validate
